#NumPy Cheet Sheet

This Numpy library is the core library for scientific computing in Python. It provides a high-performance multi-dimentional array object, and tools for working with these arrays. 

In [79]:
import numpy as np

#Creating Arrays

In [80]:
#1D Array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [81]:
#2D Array
b = np.array([(1.5, 2, 3),(4, 5, 6)], dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [82]:
#3D Array
c = np.array([[(1.5, 2, 3), (4, 5, 6)],[(3, 2, 1), (4, 5, 6)]], dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

#Initial Placeholders

In [83]:
np.zeros((3,4)) # Create an array of Zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.ones((2, 3, 4), dtype=np.int64) # Create an array of Ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [85]:
d = np.arange(10, 25, 5) # Create an array of evenly spaced values(step value)
d

array([10, 15, 20])

In [86]:
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [87]:
e = np.full((2, 2), 7) # Create a constant array
e

array([[7, 7],
       [7, 7]])

In [88]:
f = np.eye(2) # Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [89]:
np.random.random((2,2)) #Create an array with random values

array([[0.14946831, 0.20123169],
       [0.29100971, 0.40882434]])

In [90]:
np.empty((3,2)) #Create an emtpy array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

#I/O

##Saving & Loading on Disk

In [91]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([1, 2, 3, 4])

##Saving & Loading Text Files

In [92]:
np.savetxt("myarray.txt", a, delimiter=" ")
np.genfromtxt("myarray.txt", delimiter=",")
np.loadtxt("myarray.txt")

array([1., 2., 3., 4.])

#Data Types

In [93]:
np.int64 # Signed 64-bit integer types
np.float32 # Standard double-precision floating point
np.complex # Complex numbers represented by 128 floats
np.bool # Boolean type storing TRUE and FALSE values
np.object # python object type
np.string_ # Fixed-length string type
np.unicode_ # Fixed-length unicode type

numpy.str_

#Inspecting your Array

In [94]:
a.shape #Array dimensions
len(a) #Length of Array
b.ndim #Number of array dimentions
e.size # Number of array elements
b.dtype #Data type pf array elements
b.dtype.name #Name of data type
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

#Asking For Help

In [95]:
np.info(np.ndarray.dtype)

#Array Mathematics

## Arthematic Operations

In [96]:
g = np.array([1, 3, 2, 6, 5])
h = np.array([4, 3, 2, 1, 3])

In [97]:
i = g-h #Subtraction
g

array([1, 3, 2, 6, 5])

In [98]:
np.subtract(g,h) # Subtraction

array([-3,  0,  0,  5,  2])

In [99]:
g+h # Addition

array([5, 6, 4, 7, 8])

In [100]:
np.add(g, h) # Addition

array([5, 6, 4, 7, 8])

In [101]:
g/h # Division

array([0.25      , 1.        , 1.        , 6.        , 1.66666667])

In [102]:
np.divide(g, h) # Division

array([0.25      , 1.        , 1.        , 6.        , 1.66666667])

In [103]:
g*h # Multiplication

array([ 4,  9,  4,  6, 15])

In [104]:
np.multiply(g, h) # Multiplication

array([ 4,  9,  4,  6, 15])

In [105]:
np.exp(h) #Exponentiation

array([54.59815003, 20.08553692,  7.3890561 ,  2.71828183, 20.08553692])

In [106]:
np.sqrt(h) #Square root

array([2.        , 1.73205081, 1.41421356, 1.        , 1.73205081])

In [107]:
np.sin(g) #Print sines of an array

array([ 0.84147098,  0.14112001,  0.90929743, -0.2794155 , -0.95892427])

In [108]:
np.cos(h) #Element-wise cosine

array([-0.65364362, -0.9899925 , -0.41614684,  0.54030231, -0.9899925 ])

In [109]:
np.log(g) #Element-wise natural logarithm

array([0.        , 1.09861229, 0.69314718, 1.79175947, 1.60943791])

In [110]:
e.dot(f) # Dot product

array([[7., 7.],
       [7., 7.]])

## Comparison

In [111]:
g == h #Element-wise comparision

array([False,  True,  True, False, False])

In [112]:
g < 2 #Element-wise comparision

array([ True, False, False, False, False])

In [113]:
np.array_equal(g, h) #Array-wise comparision

False

##Aggregate Functions

In [114]:
g.sum() #Array-wise sum

17

In [115]:
g.min() #Array-wise minimum value

1

In [116]:
h.max(axis=0) #Maximum value of an array row

4

In [117]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [118]:
b.cumsum(axis=0) # Cumulative sum of the elements

array([[1.5, 2. , 3. ],
       [5.5, 7. , 9. ]])

In [119]:
g.mean() #Mean

3.4

In [120]:
np.median(b) #Median

3.5

In [121]:
np.corrcoef(a) #Correlation Coefficient

1.0

In [122]:
np.std(b) #Standard Deviation

1.5920810978785667

#Copying Arrays

In [123]:
h = a.view() #Create a view of the array with the same data
np.copy(a)
h=a.copy()
h

array([1, 2, 3, 4])

#Sorting Array

In [124]:
a.sort() #Sort a array
a

array([1, 2, 3, 4])

In [126]:
b.sort()
reversed_array = b[::-1] # Sort a array in reversed order
reversed_array

array([[4. , 5. , 6. ],
       [1.5, 2. , 3. ]])

In [127]:
c.sort(axis=1) #Sort the elements of an array's axis
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

#Subsetting, Slicing, Indexing

##Subsetting

In [128]:
a

array([1, 2, 3, 4])

In [129]:

a[2]

3

##Slicing

In [130]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [143]:
a

array([1, 2, 3, 4])

In [131]:
a[0:2] # Select items at 0 and 1

array([1, 2])

In [132]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [133]:
b[0:2,1] #Select items at rows 0 and 1 in column 1  

array([2., 5.])

In [135]:
b[:1] # Select all values at row 0 (equivalent to b[0:1,:])

array([[1.5, 2. , 3. ]])

In [138]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [137]:
c[1,...] #Same as [1,:,:]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [139]:
a[::-1] #Reversed Array a

array([4, 3, 2, 1])

##Boolean Indexing

In [140]:
a[a<2] #Select elements from a less than 2

array([1])

##Fancy Indexing

In [142]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [141]:
b[[1,0,1,0],[0,1,2,0]] #Select elements (1,0), (0,1), (1,2), (0,0)

array([4. , 2. , 6. , 1.5])

In [144]:
b[[1,0,1,0]][:,[0,1,2,0]] #Select subset of the matrix's rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

#Array Manipulation

##Transposing Array

In [154]:
j = np.transpose(b) #Premute array dimentions
j

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [155]:
j.T #Premute array dimentions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

##Change Array Shape

In [156]:
b.ravel() #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [160]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [161]:
c.reshape(3,-2) #Reshape but don't change data

array([[1.5, 2. , 3. , 4. ],
       [5. , 6. , 3. , 2. ],
       [1. , 4. , 5. , 6. ]])

##Adding/Removing Elements

In [164]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [167]:
c.resize((2,6)) #Return new array with shape(2,6)
c

array([[1.5, 2. , 3. , 4. , 5. , 6. ],
       [3. , 2. , 1. , 4. , 5. , 6. ]])

In [168]:
h

array([1, 2, 3, 4])

In [169]:
g

array([1, 3, 2, 6, 5])

In [170]:
np.append(h,g) #Appends items to an array

array([1, 2, 3, 4, 1, 3, 2, 6, 5])

In [171]:
np.insert(a,1,5) #Insert items in an array

array([1, 5, 2, 3, 4])

In [172]:
np.delete(a, [1]) #Delete items from an array

array([1, 3, 4])

##Combining arrays

In [173]:
np.concatenate((a,d), axis=0) #Concatenate arrays

array([ 1,  2,  3,  4, 10, 15, 20])

In [188]:
a = np.array([1, 2, 3])

In [187]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [189]:
np.vstack((a, b)) #Stack arrays vertically(row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [191]:
print(e)
print(f)

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [190]:
np.r_[e,f] #stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [192]:
np.hstack((e,f)) #stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [193]:
np.column_stack((a,d)) #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [195]:
np.c_[a,d] #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

##Splitting Arrays

In [196]:
np.hsplit(a,3) #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [198]:
np.vsplit(c, 2) #Split the array vertically at the 2nd index

[array([[1.5, 2. , 3. , 4. , 5. , 6. ]]), array([[3., 2., 1., 4., 5., 6.]])]